// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3XJNk-Kw3c-LS84Yyh1C19DkbiKNjxs0',
    appId: '1:765941372951:web:48f24b1e31e8ab29482452',
    messagingSenderId: '765941372951',
    projectId: 'nithlostnfoundweb',
    authDomain: 'nithlostnfoundweb.firebaseapp.com',
    storageBucket: 'nithlostnfoundweb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXv7-j-d7i6BfNiy62eiMt07NsmVjjXQ',
    appId: '1:765941372951:android:9778c87f2be20693482452',
    messagingSenderId: '765941372951',
    projectId: 'nithlostnfoundweb',
    storageBucket: 'nithlostnfoundweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxi2z0F_-uNBtCRKrOYzCcTs34aLPuXo',
    appId: '1:765941372951:ios:ec69e7edbeaf1278482452',
    messagingSenderId: '765941372951',
    projectId: 'nithlostnfoundweb',
    storageBucket: 'nithlostnfoundweb.appspot.com',
    iosBundleId: 'com.example.nithlostnfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuxi2z0F_-uNBtCRKrOYzCcTs34aLPuXo',
    appId: '1:765941372951:ios:ec69e7edbeaf1278482452',
    messagingSenderId: '765941372951',
    projectId: 'nithlostnfoundweb',
    storageBucket: 'nithlostnfoundweb.appspot.com',
    iosBundleId: 'com.example.nithlostnfound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3XJNk-Kw3c-LS84Yyh1C19DkbiKNjxs0',
    appId: '1:765941372951:web:59b3ad5d1e6c8b6d482452',
    messagingSenderId: '765941372951',
    projectId: 'nithlostnfoundweb',
    authDomain: 'nithlostnfoundweb.firebaseapp.com',
    storageBucket: 'nithlostnfoundweb.appspot.com',
  );
}
